pipeline{
    agent any
    stages{
        stage("Build"){
            steps{
                nodejs('node18'){
                    sh 'npm install --prefix ./client'
                    sh 'npm run build --prefix ./client'
                    sh 'tar -zcf ${JOB_NAME}${BUILD_NUMBER}.tar.gz ./client/build/*'
                }
            }
            post{
                success{
                    sh 'aws s3 cp ./${JOB_NAME}${BUILD_NUMBER}.tar.gz s3://itwaswinter0204/${JOB_NAME}${BUILD_NUMBER}.tar.gz'
                }
            }
        }
        stage("Deploy"){
            steps{
                sh '''
ansible-playbook -i ./client/ansible/front_inventory.ini ./client/ansible/frontend_playbook.yml --extra-vars "file_name='${JOB_NAME}${BUILD_NUMBER}.tar.gz'"
                   '''
            }
        }
    }
}