- name: "Deploy Backend Artifact"
  hosts: all
  become: true
  tasks:
    - name: "Download Artifact"
      shell:
        cmd: "aws s3 cp s3://itwaswinter0204/{{ filename }} /home/ec2_user/server.jar"
    - name: "Wait for Artifact"
      wait_for:
        path: /home/ec2_user/server.jar
    - name: "Deploy"
      shell:
        cmd: "sh /home/ec2-user/replaceserver.sh"
