apiVersion: apps/v1
kind: Deployment
metadata:
  name: goorm-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goorm-server
  template:
    metadata:
      labels:
        app: goorm-server
    spec:
      containers:
        - name: goorm-server
          image: boooo0/goorm-server:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: goorm-server-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: goorm-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

