pipeline{
    agent any
    stages{
        stage("Checkout Repo") {
            steps {
                cleanWs()
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/BOOOO0/architecture.git']]])
            }
        }
        stage("Build"){
            steps{
                script{
                    dir('server'){
                        sh 'chmod 777 gradlew'
                        sh './gradlew build'
                    }
                }
            }
            post{
                success{
                    sh 'aws s3 cp ./server/build/libs/server-0.0.1-SNAPSHOT.jar s3://itwaswinter0204/${JOB_NAME}${BUILD_NUMBER}.jar'
                }
            }
        }
        stage("Deploy"){
            steps{
                sh '''
ansible-playbook -i ./server/ansible/back_inventory.ini ./server/ansible/backend_playbook.yml --extra-vars "file_name='${JOB_NAME}${BUILD_NUMBER}.jar'"
                   '''
            }
        }
    }
}