apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-apps
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: backend
  template:
    metadata:
      labels:
        env: backend
    spec:
      containers:
        - name: backend-apps
          image: boooo0/backend:v3.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
  labels:
    env: backend
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    env: backend
  type: ClusterIP
