apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-apps
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: frontend
  template:
    metadata:
      labels:
        env: frontend
    spec:
      containers:
        - name: frontend-apps
          image: boooo0/frontend:v3.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
  labels:
    env: dev
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    env: frontend
  type: LoadBalancer
